sudo: required
language: perl
services:
        - docker
env:
  global:
    - CHANGELOG_NAME=Asbru-CM Team
    - CHANGELOG_EMAIL=contact@asbru-cm.net
    - PRODUCT=asbru-cm
  matrix:
    - OS=debian DIST=jessie PACKAGE=deb
    - OS=debian DIST=stretch PACKAGE=deb
    - OS=debian DIST=buster PACKAGE=deb EXECUTE_BUILD_DOCS=true
    - OS=ubuntu DIST=xenial PACKAGE=deb
    - OS=ubuntu DIST=bionic PACKAGE=deb
    - OS=ubuntu DIST=eoan PACKAGE=deb
    - OS=ubuntu DIST=focal PACKAGE=deb DOCKER_REPO=asbru/asbru-cm
    - OS=fedora DIST=29 PACKAGE=rpm
    - OS=fedora DIST=30 PACKAGE=rpm
    - OS=fedora DIST=31 PACKAGE=rpm
    - OS=el DIST=7 PACKAGE=rpm
    - OS=el DIST=8 PACKAGE=rpm
    - OS=linuxmint DIST=sonya PACKAGE=deb DOCKER_IMAGE=debian-stretch
    - OS=linuxmint DIST=sylvia PACKAGE=deb DOCKER_IMAGE=debian-stretch
    - OS=linuxmint DIST=tara PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic
    - OS=linuxmint DIST=tessa PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic
    - OS=linuxmint DIST=tina PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic
    - OS=linuxmint DIST=tricia PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic
install:
    - sudo apt-get update
    - sudo apt-get install -y git devscripts debhelper quilt python3 python3-pip python3-setuptools
    - sudo pip3 install --upgrade pip
script:
    - ./build.sh
    - bash scripts/deploy_docs.sh
deploy:
  - provider: packagecloud
    skip_cleanup: true
    repository: asbru-cm
    username: ${PACKAGECLOUD_USER}
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: "build/*.{deb,rpm,dsc}"
    on:
      tags: true
  - provider: packagecloud
    skip_cleanup: true
    repository: legacy
    username: ${PACKAGECLOUD_USER}
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: "build/*.{deb,rpm,dsc}"
    on:
      branch: legacy/6.1


after_deploy:
  # Prune old packages from packagecloud. The last 5 should be enough.
  - pip install -r ./packpack/tools/requirements.txt
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/snapshots deb ${OS} ${DIST} --keep 5
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/snapshots rpm ${OS} ${DIST} --keep 5
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/loki deb ${OS} ${DIST} --keep 5
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/loki rpm ${OS} ${DIST} --keep 5
