os: linux
dist: bionic
language: perl
services:
  - docker
env:
  global:
    - CHANGELOG_NAME=Asbru-CM Team
    - CHANGELOG_EMAIL=contact@asbru-cm.net
    - PRODUCT=asbru-cm
  jobs:
    - OS=debian DIST=jessie PACKAGE=deb PACKAGECLOUD=true
    - OS=debian DIST=stretch PACKAGE=deb PACKAGECLOUD=true
    - OS=debian DIST=buster PACKAGE=deb EXECUTE_BUILD_DOCS=true PACKAGECLOUD=true
    - OS=debian DIST=bullseye PACKAGE=deb PACKAGECLOUD=true
    - OS=ubuntu DIST=xenial PACKAGE=deb PACKAGECLOUD=true
    - OS=ubuntu DIST=bionic PACKAGE=deb PACKAGECLOUD=true
    - OS=ubuntu DIST=focal PACKAGE=deb PACKAGECLOUD=true
    - OS=ubuntu DIST=groovy PACKAGE=deb PACKAGECLOUD=true
    - OS=ubuntu DIST=hirsute PACKAGE=deb PACKAGECLOUD=true
    - OS=ubuntu DIST=impish DOCKER_REPO=asbru/asbru-cm PACKAGE=deb PACKAGECLOUD=true
    - OS=fedora DIST=29 PACKAGE=rpm PACKAGECLOUD=true
    - OS=fedora DIST=30 PACKAGE=rpm PACKAGECLOUD=true
    - OS=fedora DIST=31 PACKAGE=rpm PACKAGECLOUD=true
    - OS=fedora DIST=32 PACKAGE=rpm PACKAGECLOUD=true
    - OS=fedora DIST=33 PACKAGE=rpm PACKAGECLOUD=true
    - OS=fedora DIST=34 PACKAGE=rpm PACKAGECLOUD=true
    - OS=el DIST=7 PACKAGE=rpm PACKAGECLOUD=true
    - OS=el DIST=8 PACKAGE=rpm PACKAGECLOUD=true
    - OS=linuxmint DIST=sonya PACKAGE=deb DOCKER_IMAGE=debian-stretch PACKAGECLOUD=true
    - OS=linuxmint DIST=sylvia PACKAGE=deb DOCKER_IMAGE=debian-stretch PACKAGECLOUD=true
    - OS=linuxmint DIST=tara PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic PACKAGECLOUD=true
    - OS=linuxmint DIST=tessa PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic PACKAGECLOUD=true
    - OS=linuxmint DIST=tina PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic PACKAGECLOUD=true
    - OS=linuxmint DIST=tricia PACKAGE=deb DOCKER_IMAGE=ubuntu-bionic PACKAGECLOUD=true
    - OS=linuxmint DIST=ulyana PACKAGE=deb DOCKER_IMAGE=ubuntu-focal PACKAGECLOUD=false
    - OS=linuxmint DIST=ulyssa PACKAGE=deb DOCKER_IMAGE=ubuntu-focal PACKAGECLOUD=false
    - OS=linuxmint DIST=uma PACKAGE=deb DOCKER_IMAGE=ubuntu-focal PACKAGECLOUD=false
    - OS=pop DIST=focal PACKAGE=deb DOCKER_IMAGE=ubuntu-focal PACKAGECLOUD=false
    - OS=pop DIST=hirsute PACKAGE=deb DOCKER_IMAGE=ubuntu-hirsute PACKAGECLOUD=false
    - OS=elementary DIST=odin PACKAGE=deb DOCKER_IMAGE=ubuntu-focal PACKAGECLOUD=false
before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
    - sudo apt-get update
    - sudo apt-get install -y git devscripts debhelper quilt python3 python3-pip python3-setuptools gpgv
    - sudo pip3 install --upgrade pip
    - sudo pip3 install --upgrade cloudsmith-cli
script:
    - ./build.sh
    - bash scripts/deploy_docs.sh
deploy:
  - provider: packagecloud
    skip_cleanup: true
    repository: snapshots
    username: ${PACKAGECLOUD_USER}
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: "build/*.{deb,rpm,dsc}"
    on:
      branch: master
      condition: $PACKAGECLOUD = true
  - provider: packagecloud
    skip_cleanup: true
    repository: asbru-cm
    username: ${PACKAGECLOUD_USER}
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: "build/*.{deb,rpm,dsc}"
    on:
      tags: true
      condition: $PACKAGECLOUD = true
  - provider: packagecloud
    skip_cleanup: true
    repository: loki
    username: ${PACKAGECLOUD_USER}
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: "build/*.{deb,rpm,dsc}"
    on:
      branch: loki
      condition: $PACKAGECLOUD = true
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh snapshots
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh loki
    on:
      branch: loki
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh release
    on:
      tags: true


after_deploy:
  # Prune old packages from packagecloud. The last 5 should be enough.
  - pip install -r ./packpack/tools/requirements.txt
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/snapshots deb ${OS} ${DIST} --keep 5
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/snapshots rpm ${OS} ${DIST} --keep 5
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/loki deb ${OS} ${DIST} --keep 5
  - python ./packpack/tools/packagecloud prune ${PACKAGECLOUD_USER}/loki rpm ${OS} ${DIST} --keep 5
