site_name: Ásbrú Connection Manager - Docs
docs_dir: doc
site_dir: out
site_url: https://docs.asbru-cm.net
site_author: Ásbrú Connection Manager
site_description: Ásbrú Connection Manager user and developer documentation
repo_url: https://github.com/asbru-cm/asbru-cm
edit_uri: edit/master/doc
repo_name: GitHub
theme:
    name: material
    palette:
        primary: deep purple
        accent: pink
extra_css:
    - stylesheets/custom.css
nav:
  - Home: 'index.md'
  - 1. General:
      - News: General/News.md
      - Installation: General/Installation.md
      - Upgrade: General/Upgrade.md
      - Changelog: General/Changelog.md
      - Warning:   General/sensitive-info-notice.md
  - 2. User's Manual:
      - Quick Start: Manual/QuickStart.md
      - Preferences:
        - General: Manual/Preferences/Preferences.md
        - Main Options:
          - Behaviour: Manual/Preferences/MainOptions.md
          - Look&Feel: Manual/Preferences/LookAndFeel.md
          - Advanced: Manual/Preferences/MOAdvanced.md
        - Terminal Options:
          - Behaviour: Manual/Preferences/TermOptions.md
          - Look&Feel: Manual/Preferences/TermLookAndFeel.md
          - Advanced: Manual/Preferences/TermAdvanced.md
        - Shell Options: Manual/Preferences/ShellOptions.md
        - Networking: Manual/Preferences/Networking.md
        - Global Variables: Manual/Preferences/GlobalVariables.md
        - Local Commands: Manual/Preferences/LocalCommands.md
        - Remote Commands: Manual/Preferences/RemoteCommands.md
        - KeePass: Manual/Preferences/KeePassXC.md
        - KeyBindings: Manual/Preferences/KeyBindings.md
        - Systemtray Extensions: Manual/Preferences/SytemTrayExtensions.md
      - Command Line: Manual/CommandLine.md
      - Connections:
        - Configure: Manual/Connections/SSH.md
        - Methods:
            - SSH: Manual/Connections/SSH_Terminal.md
            - RDP: Manual/Connections/RDP.md
      - References:
        - Substitution: Manual/Substitutions.md
  - 3. Contributed Articles:
      - Clusters: Managing/Clusters.md
      - Templates: Managing/Templates.md
      - Expect: Managing/Expect.md
  - 4. Contributing:
      - Contributing: Contributing/index.md
      - Coding standards: Contributing/CODING_STANDARD.md
      - Code of conduct: Contributing/CODE_OF_CONDUCT.md

markdown_extensions:
    - admonition
    - toc:
        permalink: true
        toc_depth: 6
    - codehilite:
        guess_lang: false
