site_name: Ásbrú Connection Manager - Docs
docs_dir: doc
site_dir: out
site_url: http://docs.librenms.org
site_author: Ásbrú Connection Manager
site_description: Ásbrú Connection Manager user and developer documentation
repo_url: https://github.com/asbru-cm/asbru-cm
edit_uri: edit/master/doc
repo_name: GitHub
theme:
    name: material
nav:
  - Home: 'index.md'
  - 1. General:
      - News: General/NEWS.md
      - Installation: General/Installation.md
      - Changelog: General/Changelog.md
  - 2. User's Manual:
      - Quick Start: Manual/QuickStart.md
      - Preferences: Manual/Preferences/Preferences.md
      - Main Options Behaviour: Manual/Preferences/MainOptions.md
      - Main Options Look&Feel: Manual/Preferences/LookAndFeel.md
      - Main Options Advanced: Manual/Preferences/MOAdvanced.md
  - 3. Contributed Articles:
      - Clusters: Managing/Clusters.md
  - 4. Contributing:
      - Contributing: Contributing/index.md
      - Coding standards: Contributing/CODING_STANDARD.md
      - Code of conduct: Contributing/CODE_OF_CONDUCT.md

markdown_extensions:
  - admonition

