name: Build Release Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test:
    uses: ./.github/workflows/package-build.yml
    with:
      cloudsmith_dest: release
      packagecloud_repo: asbru-cm
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      PACKAGECLOUD_USER: ${{ secrets.PACKAGECLOUD_USER }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
