name: Build Test Packages

on:
  push:
    branches: [ build-test ]

jobs:
  build-test:
    uses: ./.github/workflows/package-build.yml
    with:
      cloudsmith_dest: test
      packagecloud_repo: test
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      PACKAGECLOUD_USER: ${{ secrets.PACKAGECLOUD_USER }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
