name: Build Snapshot/Master Packages

on:
  push:
    branches: [ master ]

jobs:
  build-test:
    uses: ./.github/workflows/package-build.yml
    with:
      cloudsmith_dest: snapshots
      packagecloud_repo: snapshots
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      PACKAGECLOUD_USER: ${{ secrets.PACKAGECLOUD_USER }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
