name: Build Loki Packages

on:
  push:
    branches: [ loki ]

jobs:
  build-test:
    uses: ./.github/workflows/package-build.yml
    with:
      cloudsmith_dest: loki
      packagecloud_repo: loki
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      PACKAGECLOUD_USER: ${{ secrets.PACKAGECLOUD_USER }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
